### ISSUE TITLE
Doesn't work with Braintree API >2.2.0

### ISSUE THREAD

**Issue by msn444** [jibon57/nativescript-braintree#26]
I get the following error if I set com.braintreepayments.api:braintree to >2.2.0 (tried 3.9.0) or com.braintreepayments.api:google-payment to > 2.0.1 (tried 3.3.1) in app.gradle:

> System.err: java.lang.NoSuchMethodError: No static method newInstance(Landroid/app/Activity;Ljava/lang/String;)Lcom/braintreepayments/api/BraintreeFragment; in class Lcom/braintreepayments/api/BraintreeFragment; or its super classes (declaration of 'com.braintreepayments.api.BraintreeFragment' appears in /data/app/com.skywaylabs.WiSPLICE-YTPT-naKxfajuYllifOdJg==/base.apk)
> 
> System.err: 	at com.braintreepayments.api.dropin.BaseActivity.getBraintreeFragment(BaseActivity.java:62)
> 
> System.err: 	at com.braintreepayments.api.dropin.DropInActivity.onCreate(DropInActivity.java:109)
>
